import localFont from "next/font/local";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
        {children}



        <h1 className="h-50 p-5 bg-green-500 text-6xl text-gray-900 dark:text-white">
          Layout Contant
        </h1>

      </body>
    </html>
  );
}
